server:
  port: 0
security:
  oauth2:
    resource:
      user-info-uri: https://dev-826281.oktapreview.com/oauth2/default/v1/userinfo
      prefer-token-info: false

management:
  endpoints:
    web:
      exposure:
        include: beans,mappings
        
spring:
  data:
    mongodb:
      uri: mongodb://mongoadmin:secret@localhost:27013/character?authSource=admin
  cloud:
    config:
      overrideSystemProperties: false
