spring:
  cloud:
    config:
      uri: ${CONFIG_URI}
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false
    service-url:
      defaultZone: ${EUREKA_URL}
    
