
server:
  port: 6673
  servlet:
    context-path: /payment-service
security:
  oauth2:
    resource:
      user-info-uri: https://dev-826281.oktapreview.com/oauth2/default/v1/userinfo
      prefer-token-info: false

feign:
  hystrix:
    enabled: true
hystrix:
  shareSecurityContext: true

spring:
  data:
    mongodb:
      uri: ${DATABASE_URI}
  cloud:
    config:
      overrideSystemProperties: false
eureka:
  instance:
    hostname: payment-service
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
      
stripe:
  api:
    key: *
